spring:

  datasource:
    url:
    username:
    password:

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

jwt-token:
  expiring-days: 30

aws:
  access-key-id:
  secret-access-key:
  region:

  bucket:
    name:
    users-folder:
    apartments-folder:

server:
  port: 443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/hotel-booking-service.p12
    key-store-password:
    key-alias:

