spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

jwt-token:
  expiring-days: 30

activation-code:
  length: 60

aws:
  access-key-id: AKIA2VXUQKUE74F2Z57O
  secret-access-key: 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
  region: eu-north-1
  bucket:
    name: hotel-booking-service-heroku
    users-folder: users/
    apartments-folder: apartments/

calendar:
  i-cal:
    prod-id-name: Apartments Pelhrimov Booking service
  zone-id: Europe/Prague
  reservation-hours:
    start: 15
    end: 11

server:
  ssl:
    enabled: false


mail:
  user: 9mohapx9@gmail.com
  password: knknuxiivdlhklwo
  smtp:
    host: smtp.gmail.com
    port: 587
    tarttls:
      enable: true
