spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_booking_service
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

cors:
  allowed-origins: "*"
  allowed-methods: "*"

jwt:
  validForDays: 30
  issuer: https://apartmany-pe.cz/

activation-code:
  length: 60

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  region: eu-north-1
  bucket:
    name: hotel-booking-service-dev

server:
  port: 443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/hotel-booking-service.p12
    key-store-password: 210605
    key-alias: hotel-booking-service

calendar:
  i-cal:
    prod-id: Apartments Pelhrimov Booking service
  zone-id: Europe/Prague
  reservation-hours:
    start: 15
    end: 11

mail:
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  developers: 9mohapx9@gmail.com,balakhon.michael@lll.kpi.ua
  smtp:
    host: smtp.gmail.com
    port: 587
    starttls:
      enable: true

localized-bundles.paths:
  - classpath:localized/mail
  - classpath:localized/messages
