spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate.ddl-auto: validate
  flyway:
    baseline-on-migrate: true

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

jwt:
  valid-for-days: 30
  issuer: https://apartmany-pe.cz/

token:
  length: 60
  valid-for-minutes: 30

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
  allowed-methods: ${CORS_ALLOWED_METHODS}

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  region: eu-north-1
  bucket.name: hotel-booking-service-heroku

calendar:
  i-cal.prod-id: Apartments Pelhrimov Booking service
  zone-id: Europe/Prague
  reservation-hours:
    start: 15
    end: 11

server.ssl.enabled: false

mail:
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  developers: ${MAIL_DEVELOPERS}
  smtp:
    host: smtp.gmail.com
    port: 587
    starttls.enable: true

localized-bundles.paths:
  - classpath:localized/mail
  - classpath:localized/messages
