spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_booking_service
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate.ddl-auto: validate
    properties:
      hibernate.format_sql: true
  flyway:
    baseline-on-migrate: true
    fail-on-missing-locations: true
    validate-migration-naming: true
  servlet.multipart:
    max-file-size: 3072KB # 3MB
    max-request-size: 6144KB # 6MB

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

cors:
  allowed-origins: "*"
  allowed-methods: "*"

jwt:
  valid-for-days: 30
  issuer: https://apartmany-pe.cz/

token:
  length: 60
  valid-for-minutes: 30

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  region: eu-north-1
  bucket.name: hotel-booking-service-dev

server:
  port: 443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/hotel-booking-service.p12
    key-store-password: 210605
    key-alias: hotel-booking-service

calendar:
  i-cal.prod-id: Apartments Pelhrimov Booking service
  zone-id: Europe/Prague
  reservation-hours:
    start: 15
    end: 11

mail:
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  smtp:
    host: smtp.gmail.com
    port: 587
    starttls.enable: true

localized-bundles.paths:
  - classpath:localized/mail
  - classpath:localized/messages

app:
  name: Apartmány Pelhřimov service
  version: 0.0.1-SNAPSHOT
  contact-link: https://apartmany-pe.cz/
  email:
  developer-emails:
  locale:
