spring:

  datasource:
    url:
    username:
    password:

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

jwt-token:
  expiring-days: 30

aws:
  access-key-id:
  secret-access-key:
  region:

  bucket:
    apartments-folder:
    name:
    users-folder:
