openapi: "3.0.3"
info:
  title: "hotel_booking_service API"
  description: "hotel_booking_service API"
  version: "1.0.0"
servers:
  - url: "https://localhost"
paths:
  /api/users/me:
    get:
      security:
        - bearer: [ ]
      summary: "GET api/users/me"
      operationId: "getOne"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserDto"
components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UserDto:
      type: "object"
      properties:
        firstName:
          type: "string"
        lastName:
          type: "string"
        photo:
          type: "string"
        role:
          type: "string"
          enum:
            - "USER"
            - "MANAGER"
